# Generated by Django 4.2.29 on 2026-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_inventoryitem_invoice_appointment_is_virtual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='condition',
            new_name='condition_name',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='notes',
            new_name='treatment_plan',
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration_days',
            field=models.IntegerField(default=7),
        ),
    ]
