# Generated by Django 4.2.29 on 2026-04-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_appointment_priority_symptomcheck_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetail',
            name='alcohol_consumption',
            field=models.CharField(choices=[('None', 'None'), ('Occasional', 'Occasional'), ('Frequent', 'Frequent')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='smoking_status',
            field=models.CharField(choices=[('Never', 'Never'), ('Former', 'Former'), ('Current', 'Current Smoker')], default='Never', max_length=20),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
