# Generated by Django 4.2.29 on 2026-04-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_persondetail_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetail',
            name='assigned_doctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='chronic_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='current_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
