# Generated by Django 4.2.29 on 2026-04-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_persondetail_assigned_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomcheck',
            name='dosage_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='medication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
