from collections import OrderedDict
from decimal import Decimal
from io import BytesIO

from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy
from django.http import FileResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from .models import PersonDetail, Appointment, MedicalReport, Doctor, Invoice, Payment, InventoryItem, StockTransaction, MedicalHistory, Prescription, Message, SymptomCheck, User
from .ai_utils import (
    detect_appointment_priority,
    get_ai_response,
    get_nearby_healthcare,
    predict_disease_from_symptoms,
)
from django.contrib import messages
from django.contrib.auth.views import LoginView as DjangoLoginView
from django.contrib.auth import logout, login
from django.db.models import Count, Sum
from django.utils import timezone
from django import forms
from PIL import Image, ImageDraw, ImageFont
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


def _draw_wrapped_text(draw, text, position, font, max_width, fill, line_spacing=8):
    x, y = position
    words = (text or '').split()
    if not words:
        return y

    line = []
    for word in words:
        test_line = " ".join(line + [word])
        bbox = draw.textbbox((x, y), test_line, font=font)
        if bbox[2] - bbox[0] <= max_width:
            line.append(word)
            continue
        draw.text((x, y), " ".join(line), font=font, fill=fill)
        y += (bbox[3] - bbox[1]) + line_spacing
        line = [word]

    if line:
        bbox = draw.textbbox((x, y), " ".join(line), font=font)
        draw.text((x, y), " ".join(line), font=font, fill=fill)
        y += (bbox[3] - bbox[1]) + line_spacing
    return y


def _build_invoice_pdf(invoice):
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    pdf.setFillColor(colors.HexColor('#0f172a'))
    pdf.rect(0, height - 55 * mm, width, 55 * mm, fill=1, stroke=0)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(20 * mm, height - 22 * mm, "EHR DATA INVOICE")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(20 * mm, height - 30 * mm, "Healthcare Billing Statement")

    pdf.setFillColor(colors.HexColor('#0f172a'))
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(20 * mm, height - 72 * mm, f"Invoice #: INV-{invoice.id:04d}")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(20 * mm, height - 80 * mm, f"Issue Date: {timezone.localtime(invoice.issued_date).strftime('%d %b %Y %I:%M %p') if invoice.issued_date else 'N/A'}")
    pdf.drawString(20 * mm, height - 87 * mm, f"Status: {invoice.status}")
    pdf.drawString(20 * mm, height - 94 * mm, f"Patient: {invoice.patient.full_name}")
    pdf.drawString(20 * mm, height - 101 * mm, f"Contact: {invoice.patient.mobile_number or 'N/A'}")
    pdf.drawString(20 * mm, height - 108 * mm, f"Email: {invoice.patient.email or 'N/A'}")
    pdf.drawString(20 * mm, height - 115 * mm, f"Address: {invoice.patient.address_line1 or 'Not provided'}")

    y = height - 138 * mm
    pdf.setFillColor(colors.HexColor('#eff6ff'))
    pdf.roundRect(18 * mm, y - 8 * mm, width - 36 * mm, 16 * mm, 4 * mm, fill=1, stroke=0)
    pdf.setFillColor(colors.HexColor('#1d4ed8'))
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(24 * mm, y - 1 * mm, "Billing Summary")

    pdf.setFillColor(colors.HexColor('#0f172a'))
    pdf.setFont("Helvetica", 11)
    pdf.drawString(24 * mm, y - 15 * mm, f"Consultation / Services")
    pdf.drawRightString(width - 24 * mm, y - 15 * mm, f"Rs. {invoice.total_amount}")
    pdf.drawString(24 * mm, y - 24 * mm, f"Payments Received")
    paid_amount = sum((payment.amount_paid for payment in invoice.payments.all()), Decimal('0.00'))
    pdf.drawRightString(width - 24 * mm, y - 24 * mm, f"Rs. {paid_amount:.2f}")
    pdf.drawString(24 * mm, y - 33 * mm, f"Outstanding")
    outstanding = max(Decimal('0.00'), invoice.total_amount - paid_amount)
    pdf.drawRightString(width - 24 * mm, y - 33 * mm, f"Rs. {outstanding:.2f}")

    if invoice.appointment:
        pdf.drawString(24 * mm, y - 48 * mm, f"Appointment")
        pdf.drawRightString(
            width - 24 * mm,
            y - 48 * mm,
            timezone.localtime(invoice.appointment.appointment_date).strftime('%d %b %Y %I:%M %p')
        )

    pdf.setStrokeColor(colors.HexColor('#cbd5e1'))
    pdf.line(20 * mm, 28 * mm, width - 20 * mm, 28 * mm)
    pdf.setFont("Helvetica", 9)
    pdf.setFillColor(colors.HexColor('#475569'))
    pdf.drawString(20 * mm, 20 * mm, "Generated by EHR Data billing module")
    pdf.drawRightString(width - 20 * mm, 20 * mm, "This is a computer-generated invoice")

    pdf.showPage()
    pdf.save()
    buffer.seek(0)
    return buffer


def _build_invoice_image(invoice):
    width, height = 1400, 1900
    image = Image.new('RGB', (width, height), '#f8fafc')
    draw = ImageDraw.Draw(image)
    title_font = ImageFont.load_default()
    body_font = ImageFont.load_default()

    draw.rounded_rectangle((60, 60, width - 60, height - 60), radius=28, fill='white', outline='#cbd5e1', width=2)
    draw.rounded_rectangle((60, 60, width - 60, 280), radius=28, fill='#0f172a')
    draw.text((110, 120), "EHR DATA INVOICE", fill='white', font=title_font)
    draw.text((110, 170), f"Invoice #: INV-{invoice.id:04d}", fill='white', font=body_font)

    lines = [
        f"Patient: {invoice.patient.full_name}",
        f"Issue Date: {timezone.localtime(invoice.issued_date).strftime('%d %b %Y %I:%M %p') if invoice.issued_date else 'N/A'}",
        f"Status: {invoice.status}",
        f"Mobile: {invoice.patient.mobile_number or 'N/A'}",
        f"Email: {invoice.patient.email or 'N/A'}",
        f"Address: {invoice.patient.address_line1 or 'Not provided'}",
        "",
        f"Invoice Total: Rs. {invoice.total_amount}",
        f"Payments Received: Rs. {sum((payment.amount_paid for payment in invoice.payments.all()), Decimal('0.00')):.2f}",
    ]
    outstanding = max(Decimal('0.00'), invoice.total_amount - sum((payment.amount_paid for payment in invoice.payments.all()), Decimal('0.00')))
    lines.append(f"Outstanding Balance: Rs. {outstanding:.2f}")
    if invoice.appointment:
        lines.append(f"Appointment: {timezone.localtime(invoice.appointment.appointment_date).strftime('%d %b %Y %I:%M %p')}")

    current_y = 350
    for line in lines:
        current_y = _draw_wrapped_text(draw, line, (110, current_y), body_font, width - 220, '#0f172a', line_spacing=14)

    draw.text((110, height - 160), "Generated by EHR Data", fill='#475569', font=body_font)
    draw.text((110, height - 120), "Computer-generated billing invoice image", fill='#475569', font=body_font)

    buffer = BytesIO()
    image.save(buffer, format='PNG')
    buffer.seek(0)
    return buffer


def _build_report_pdf(report):
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    pdf.setFillColor(colors.HexColor('#14532d'))
    pdf.rect(0, height - 55 * mm, width, 55 * mm, fill=1, stroke=0)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(20 * mm, height - 22 * mm, "MEDICAL REPORT")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(20 * mm, height - 30 * mm, "Records and Labs Summary")

    pdf.setFillColor(colors.HexColor('#0f172a'))
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(20 * mm, height - 72 * mm, f"Report #: RP-{report.id:04d}")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(20 * mm, height - 80 * mm, f"Patient: {report.patient.full_name}")
    pdf.drawString(20 * mm, height - 87 * mm, f"Report Type: {report.report_type}")
    pdf.drawString(20 * mm, height - 94 * mm, f"Report Date: {report.report_date.strftime('%d %b %Y') if report.report_date else 'N/A'}")
    pdf.drawString(20 * mm, height - 101 * mm, f"Status: {report.status}")
    pdf.drawString(20 * mm, height - 108 * mm, f"Source File: {report.file_path.name if report.file_path else 'Not uploaded'}")

    pdf.setFillColor(colors.HexColor('#f8fafc'))
    pdf.roundRect(18 * mm, height - 185 * mm, width - 36 * mm, 68 * mm, 4 * mm, fill=1, stroke=0)
    pdf.setFillColor(colors.HexColor('#0f172a'))
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(24 * mm, height - 125 * mm, "Clinical Summary")

    text_object = pdf.beginText(24 * mm, height - 136 * mm)
    text_object.setFont("Helvetica", 11)
    summary = report.summary_ai or "No clinical summary has been entered yet."
    words = summary.split()
    line = []
    for word in words:
        test_line = " ".join(line + [word])
        if pdf.stringWidth(test_line, "Helvetica", 11) <= width - 52 * mm:
            line.append(word)
            continue
        text_object.textLine(" ".join(line))
        line = [word]
    if line:
        text_object.textLine(" ".join(line))
    pdf.drawText(text_object)

    pdf.setStrokeColor(colors.HexColor('#cbd5e1'))
    pdf.line(20 * mm, 28 * mm, width - 20 * mm, 28 * mm)
    pdf.setFont("Helvetica", 9)
    pdf.setFillColor(colors.HexColor('#475569'))
    pdf.drawString(20 * mm, 20 * mm, "Generated by EHR Data records and labs module")
    pdf.drawRightString(width - 20 * mm, 20 * mm, "Computer-generated medical report")

    pdf.showPage()
    pdf.save()
    buffer.seek(0)
    return buffer


def _build_report_image(report):
    width, height = 1400, 1900
    image = Image.new('RGB', (width, height), '#f8fafc')
    draw = ImageDraw.Draw(image)
    title_font = ImageFont.load_default()
    body_font = ImageFont.load_default()

    draw.rounded_rectangle((60, 60, width - 60, height - 60), radius=28, fill='white', outline='#cbd5e1', width=2)
    draw.rounded_rectangle((60, 60, width - 60, 280), radius=28, fill='#14532d')
    draw.text((110, 120), "MEDICAL REPORT", fill='white', font=title_font)
    draw.text((110, 170), f"Report #: RP-{report.id:04d}", fill='white', font=body_font)

    current_y = 340
    header_lines = [
        f"Patient: {report.patient.full_name}",
        f"Report Type: {report.report_type}",
        f"Report Date: {report.report_date.strftime('%d %b %Y') if report.report_date else 'N/A'}",
        f"Status: {report.status}",
        f"Source File: {report.file_path.name if report.file_path else 'Not uploaded'}",
        "",
        "Clinical Summary:",
    ]
    for line in header_lines:
        current_y = _draw_wrapped_text(draw, line, (110, current_y), body_font, width - 220, '#0f172a', line_spacing=14)

    current_y += 10
    current_y = _draw_wrapped_text(
        draw,
        report.summary_ai or "No clinical summary has been entered yet.",
        (110, current_y),
        body_font,
        width - 220,
        '#0f172a',
        line_spacing=14
    )

    draw.text((110, height - 150), "Generated by EHR Data records and labs module", fill='#475569', font=body_font)
    buffer = BytesIO()
    image.save(buffer, format='PNG')
    buffer.seek(0)
    return buffer


class LandingPageView(TemplateView):
    template_name = 'management/landing.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['landing_total_patients'] = PersonDetail.objects.count()
        context['landing_total_reports'] = MedicalReport.objects.count()
        context['landing_total_ai_scans'] = SymptomCheck.objects.count()
        return context


class DashboardView(TemplateView):
    template_name = 'management/index.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            if user.role == 'Admin' or user.is_staff:
                context['role'] = 'Admin'
                context['total_patients'] = PersonDetail.objects.count()
                context['total_appointments'] = Appointment.objects.count()
                from decimal import Decimal
                context['total_revenue'] = Invoice.objects.filter(status='Paid').aggregate(Sum('total_amount'))['total_amount__sum'] or Decimal('0.00')
                context['pending_revenue'] = Invoice.objects.filter(status='Unpaid').aggregate(Sum('total_amount'))['total_amount__sum'] or Decimal('0.00')

                total_billed = context['total_revenue'] + context['pending_revenue']
                if total_billed > 0:
                    context['collection_rate'] = (context['total_revenue'] / total_billed) * 100
                else:
                    context['collection_rate'] = 0

                context['recent_appointments'] = Appointment.objects.order_by('-appointment_date')[:5]

                context['blood_summary'] = PersonDetail.objects.values('blood_group').annotate(count=Count('blood_group'))

                # Revenue Chart Data (Last 30 days)
                revenue_rows = Invoice.objects.filter(
                    status='Paid',
                    issued_date__isnull=False,
                    issued_date__gte=timezone.now() - timezone.timedelta(days=30),
                ).order_by('issued_date').values_list('issued_date', 'total_amount')

                revenue_totals = OrderedDict()
                for issued_date, total_amount in revenue_rows:
                    local_date = timezone.localtime(issued_date).date()
                    revenue_totals[local_date] = revenue_totals.get(local_date, 0) + float(total_amount or 0)

                context['revenue_labels'] = [day.strftime('%d %b') for day in revenue_totals.keys()]
                context['revenue_values'] = list(revenue_totals.values())
                context['pending_revenue'] = Invoice.objects.filter(status='Unpaid').aggregate(Sum('total_amount'))['total_amount__sum'] or 0
            elif user.role == 'Doctor':
                context['role'] = 'Doctor'
                doctor = Doctor.objects.get(user=user)
                context['doctor'] = doctor
                context['my_appointments'] = Appointment.objects.filter(doctor=doctor).order_by('appointment_date')
                context['pending_appointments'] = context['my_appointments'].filter(status='Scheduled').count()
                context['today_appointments'] = context['my_appointments'].filter(appointment_date__date=timezone.now().date())
            else:
                context['role'] = 'Patient'
                if hasattr(user, 'person') and user.person:
                    context['patient'] = user.person
                    context['appointments'] = Appointment.objects.filter(patient=user.person).order_by('-appointment_date')
                    context['reports'] = MedicalReport.objects.filter(patient=user.person).order_by('-report_date')
                    context['invoices'] = Invoice.objects.filter(patient=user.person).order_by('-issued_date')
        return context


@csrf_exempt
def symptom_checker(request):
    if request.method == 'POST':
        try:
            symptoms = request.POST.get('symptoms', '').strip()
            if not symptoms:
                return JsonResponse({'error': 'Symptoms cannot be empty'}, status=400)

            disease, prob, spec, med, dosage = predict_disease_from_symptoms(symptoms)

            if request.user.is_authenticated:
                SymptomCheck.objects.create(
                    patient=request.user,
                    symptoms=symptoms,
                    predicted_disease=disease,
                    probability=prob,
                    suggested_specialization=spec,
                    medication=med,
                    dosage_instructions=dosage
                )
            return JsonResponse({
                'disease': disease,
                'probability': prob,
                'specialization': spec,
                'medication': med,
                'dosage': dosage
            })
        except Exception as e:
            import logging
            logging.exception('Symptom checker error')
            return JsonResponse({'error': f'Server error: {str(e)}'}, status=500)
    return render(request, 'management/symptom_checker.html')


def telemedicine_room(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'POST':
        content = request.POST.get('content')
        if content:
            Message.objects.create(appointment=appointment, sender=request.user, content=content)
            return redirect('telemedicine_room', appointment_id=appointment_id)

    messages = appointment.messages.all().order_by('timestamp')
    return render(request, 'management/telemedicine.html', {
        'appointment': appointment,
        'messages': messages
    })


def generate_prescription(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'POST':
        Prescription.objects.create(
            appointment=appointment,
            medication_name=request.POST.get('medication_name'),
            dosage=request.POST.get('dosage'),
            instructions=request.POST.get('instructions'),
            duration_days=request.POST.get('duration_days', 7)
        )
        return redirect('dashboard')
    return render(request, 'management/generate_prescription.html', {'appointment': appointment})


def view_prescription(request, prescription_id):
    prescription = get_object_or_404(Prescription, id=prescription_id)
    return render(request, 'management/prescription_detail.html', {'prescription': prescription})


def review_report(request, report_id):
    report = get_object_or_404(MedicalReport, id=report_id)
    if request.method == 'POST':
        report.status = request.POST.get('status', 'Reviewed')
        report.summary_ai = request.POST.get('summary_ai', '')
        report.save()
        return redirect('report_list')
    return render(request, 'management/review_report.html', {'report': report})


def analytics_dashboard(request):
    # Clinical Insights
    disease_trends = SymptomCheck.objects.values('predicted_disease').annotate(count=Count('predicted_disease')).order_by('-count')[:5]

    # Operational Throughput (Last 7 days)
    visit_rows = Appointment.objects.filter(
        appointment_date__isnull=False,
        appointment_date__gte=timezone.now() - timezone.timedelta(days=7),
    ).order_by('appointment_date').values_list('appointment_date', flat=True)
    visit_totals = OrderedDict()
    for appointment_date in visit_rows:
        local_day = timezone.localtime(appointment_date).date()
        visit_totals[local_day] = visit_totals.get(local_day, 0) + 1

    # Inventory Health
    total_inventory = InventoryItem.objects.count()
    from django.db.models import F
    low_stock_count = InventoryItem.objects.filter(quantity__lte=F('threshold')).count()

    # Department Loading (Dynamic Real-time data)
    today_appointments = Appointment.objects.filter(appointment_date__date=timezone.now().date()).count()
    opd_load = min(100, int((today_appointments / 20) * 100)) if today_appointments > 0 else 10

    pharmacy_load = min(100, int((low_stock_count / max(1, total_inventory)) * 100)) if total_inventory > 0 else 0

    pending_reports = MedicalReport.objects.filter(status='Pending').count()
    lab_load = min(100, int((pending_reports / 10) * 100)) if pending_reports > 0 else 15

    dept_load = [
        {'name': 'OPD', 'load': opd_load},
        {'name': 'Radiology', 'load': 30},  # Baseline
        {'name': 'Pharmacy', 'load': pharmacy_load},
        {'name': 'Laboratory', 'load': lab_load}
    ]

    return render(request, 'management/analytics.html', {
        'disease_trends': list(disease_trends),
        'visit_labels': [day.strftime('%a') for day in visit_totals.keys()],
        'visit_counts': list(visit_totals.values()),
        'total_inventory': total_inventory,
        'low_stock_count': low_stock_count,
        'dept_load': dept_load,
        'total_patients': PersonDetail.objects.count(),
        'ai_run_count': SymptomCheck.objects.filter(created_at__gte=timezone.now() - timezone.timedelta(days=30)).count()
    })


def nearby_healthcare_api(request):
    lat = request.GET.get('lat')
    lon = request.GET.get('lon')

    if lat is None or lon is None:
        return JsonResponse({'error': 'Latitude and longitude are required.'}, status=400)

    try:
        providers = get_nearby_healthcare(lat, lon)
    except Exception as exc:
        return JsonResponse({'error': f'Unable to fetch providers: {exc}'}, status=500)

    return JsonResponse({'providers': providers})


def download_invoice_pdf(request, invoice_id):
    invoice = get_object_or_404(Invoice.objects.select_related('patient', 'appointment').prefetch_related('payments'), id=invoice_id)
    return FileResponse(
        _build_invoice_pdf(invoice),
        as_attachment=True,
        filename=f'invoice-{invoice.id:04d}.pdf',
        content_type='application/pdf',
    )


def download_invoice_image(request, invoice_id):
    invoice = get_object_or_404(Invoice.objects.select_related('patient', 'appointment').prefetch_related('payments'), id=invoice_id)
    return FileResponse(
        _build_invoice_image(invoice),
        as_attachment=True,
        filename=f'invoice-{invoice.id:04d}.png',
        content_type='image/png',
    )


def download_report_pdf(request, report_id):
    report = get_object_or_404(MedicalReport.objects.select_related('patient'), id=report_id)
    return FileResponse(
        _build_report_pdf(report),
        as_attachment=True,
        filename=f'medical-report-{report.id:04d}.pdf',
        content_type='application/pdf',
    )


def download_report_image(request, report_id):
    report = get_object_or_404(MedicalReport.objects.select_related('patient'), id=report_id)
    return FileResponse(
        _build_report_image(report),
        as_attachment=True,
        filename=f'medical-report-{report.id:04d}.png',
        content_type='image/png',
    )


# ============================================================
#  AUTH: Login, Logout, Registration
# ============================================================

class LoginView(DjangoLoginView):
    template_name = 'management/login.html'

    def get_success_url(self):
        return reverse_lazy('dashboard')


def logout_view(request):
    logout(request)
    return redirect('home')


class RegistrationForm(forms.ModelForm):
    full_name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control-custom', 'placeholder': 'e.g. John Doe'}),
        label='Full Name',
    )
    phone = forms.CharField(
        max_length=15,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control-custom', 'placeholder': '+91 9876543210'}),
        label='Phone Number',
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control-custom', 'placeholder': '••••••••'}),
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control-custom', 'placeholder': '••••••••'}),
    )

    class Meta:
        model = User
        fields = ['full_name', 'username', 'email', 'phone', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control-custom', 'placeholder': 'Choose a username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control-custom', 'placeholder': 'your@email.com'}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exists():
            raise forms.ValidationError("An account with this email already exists.")
        return email

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        user.role = 'Patient'
        full_name = self.cleaned_data.get('full_name', '').strip()
        parts = full_name.split(' ', 1)
        user.first_name = parts[0]
        user.last_name = parts[1] if len(parts) > 1 else ''
        if commit:
            user.save()
        return user


class PatientRegistrationView(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = 'management/register.html'
    success_url = reverse_lazy('dashboard')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('dashboard')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        response = super().form_valid(form)
        full_name = form.cleaned_data.get('full_name', '').strip() or self.object.username
        person = PersonDetail.objects.create(
            full_name=full_name,
            email=self.object.email,
            mobile_number=form.cleaned_data.get('phone', ''),
        )
        self.object.person = person
        self.object.save()
        login(self.request, self.object)
        return response


# ============================================================
#  CRUD: Persons
# ============================================================

class PersonListView(ListView):
    model = PersonDetail
    template_name = 'management/list_persons.html'
    context_object_name = 'persons'
    ordering = ['-created_at']


class PersonDetailView(DetailView):
    model = PersonDetail
    template_name = 'management/view_person.html'
    context_object_name = 'person'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['medical_histories'] = MedicalHistory.objects.filter(patient=self.object).order_by('-diagnosis_date')
        appointments = Appointment.objects.filter(patient=self.object)
        context['prescriptions'] = Prescription.objects.filter(appointment__in=appointments).order_by('-created_at')
        return context


class PersonCreateView(CreateView):
    model = PersonDetail
    template_name = 'management/add_person.html'
    fields = [
        'full_name', 'gender', 'dob', 'blood_group',
        'mobile_number', 'email', 'address_line1',
        'height_cm', 'weight_kg', 'blood_pressure',
        'chronic_conditions', 'allergies', 'emergency_contact_name',
        'emergency_contact_number', 'medical_notes'
    ]
    success_url = reverse_lazy('person_list')


class PersonUpdateView(UpdateView):
    model = PersonDetail
    template_name = 'management/add_person.html'
    fields = [
        'full_name', 'gender', 'dob', 'blood_group',
        'mobile_number', 'email', 'address_line1',
        'height_cm', 'weight_kg', 'blood_pressure',
        'chronic_conditions', 'allergies', 'emergency_contact_name',
        'emergency_contact_number', 'medical_notes'
    ]
    success_url = reverse_lazy('person_list')


class PersonDeleteView(DeleteView):
    model = PersonDetail
    template_name = 'management/confirm_delete.html'
    success_url = reverse_lazy('person_list')


class ChatbotView(TemplateView):
    template_name = 'management/chatbot.html'


# ============================================================
#  Appointments
# ============================================================

class AppointmentCreateView(CreateView):
    model = Appointment
    template_name = 'management/book_appointment.html'
    fields = ['patient', 'doctor', 'appointment_date', 'reason', 'status', 'is_virtual', 'meeting_link']
    success_url = reverse_lazy('appointment_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patients'] = PersonDetail.objects.all().order_by('full_name')
        context['doctors'] = Doctor.objects.all()
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(
            self.request,
            f"Appointment booked for {self.object.patient.full_name} with Dr. "
            f"{self.object.doctor.user.get_full_name() or self.object.doctor.user.username} on "
            f"{timezone.localtime(self.object.appointment_date).strftime('%d %b %Y %I:%M %p')}."
        )
        return response


class AppointmentListView(ListView):
    model = Appointment
    template_name = 'management/list_appointments.html'
    context_object_name = 'appointments'

    def get_queryset(self):
        queryset = Appointment.objects.select_related('patient', 'doctor__user').order_by('-appointment_date')
        user = self.request.user
        if not user.is_authenticated:
            return queryset.none()
        if user.role == 'Patient' and user.person:
            return queryset.filter(patient=user.person)
        if user.role == 'Doctor' and hasattr(user, 'doctor_profile'):
            return queryset.filter(doctor=user.doctor_profile)
        return queryset


# ============================================================
#  Medical Reports
# ============================================================

class MedicalReportCreateView(CreateView):
    model = MedicalReport
    template_name = 'management/add_report.html'
    fields = ['patient', 'report_type', 'report_date', 'file_path', 'status']
    success_url = reverse_lazy('dashboard')


class MedicalReportListView(ListView):
    model = MedicalReport
    template_name = 'management/list_reports.html'
    context_object_name = 'reports'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.role == 'Patient' and self.request.user.person:
            return queryset.filter(patient=self.request.user.person)
        return queryset


# ============================================================
#  AI Chatbot
# ============================================================

@csrf_exempt
def ask_ai(request):
    # This endpoint supports both JSON body and form-encoded POSTs.
    if request.method != 'POST':
        return JsonResponse({'answer': 'Invalid request method.'}, status=405)

    question = ''
    try:
        if request.body:
            try:
                data = json.loads(request.body)
                question = data.get('question', '')
            except json.JSONDecodeError:
                question = request.POST.get('question', '')
        else:
            question = request.POST.get('question', '')
    except Exception as e:
        # Defensive: ensure we always have a string
        question = ''

    if not question:
        return JsonResponse({'answer': 'Please ask a question.'})

    # Use the full local dataset so rule-based fallback answers are accurate.
    persons = PersonDetail.objects.order_by('-created_at')

    try:
        answer = get_ai_response(question, persons)
    except Exception as e:
        # If the AI call raises, log and fall back
        import logging
        logging.exception('AI call failed')
        answer = None

    # If AI is unavailable or returned an error string, provide a lightweight local fallback
    if not answer or isinstance(answer, str) and (
        'missing' in answer.lower() or 'error' in answer.lower() or 'connecting' in answer.lower() or 'api key' in answer.lower()
    ):
        # Simple fallback: handle a few common database questions locally
        qa = question.lower()
        # blood group lookup: "blood group of <name>"
        if 'blood group of' in qa:
            name = qa.split('blood group of')[-1].strip()
            person = PersonDetail.objects.filter(full_name__icontains=name).first()
            if person:
                answer = f"{person.full_name}'s blood group is {person.blood_group or 'Unknown'}."
            else:
                answer = "I couldn't find that person in the database."
        elif qa.startswith('who is') or qa.startswith('who was'):
            name = qa.split('who is')[-1].split('who was')[-1].strip()
            person = PersonDetail.objects.filter(full_name__icontains=name).first()
            if person:
                answer = f"{person.full_name} — {person.gender or 'N/A'}, {person.city or 'Unknown city'}; contact: {person.mobile_number or 'N/A'}."
            else:
                answer = "I couldn't find that person in the database."
        elif 'which people live in' in qa or 'who live in' in qa:
            # extract city token
            tokens = qa.split()
            city = tokens[-1]
            people = PersonDetail.objects.filter(city__icontains=city)[:10]
            if people:
                names = ', '.join([p.full_name for p in people])
                answer = f"People found in {city}: {names}."
            else:
                answer = f"No people found in {city}."
        elif 'show me all active' in qa or 'active records' in qa:
            people = PersonDetail.objects.filter(status__iexact='Active')[:20]
            if people:
                answer = 'Active records: ' + ', '.join([p.full_name for p in people])
            else:
                answer = 'No active records found.'
        else:
            # generic fallback message
            answer = answer or "AI service is currently unavailable — please try again later or check server logs."

    return JsonResponse({'answer': answer})


# ============================================================
#  Billing
# ============================================================

class BillingListView(TemplateView):
    template_name = 'management/billing_v2.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            if user.role == 'Admin' or user.is_staff:
                context['invoices'] = Invoice.objects.all().order_by('-issued_date')
                context['patients'] = PersonDetail.objects.all()
                context['total_revenue'] = (Invoice.objects.filter(status='Paid').aggregate(Sum('total_amount'))['total_amount__sum'] or 0)
                context['pending_revenue'] = (Invoice.objects.filter(status='Unpaid').aggregate(Sum('total_amount'))['total_amount__sum'] or 0)
                context['processed_today'] = Payment.objects.filter(payment_date__date=timezone.now().date()).count()
            else:
                # Patient Specific View
                if hasattr(user, 'person') and user.person:
                    patient_invoices = Invoice.objects.filter(patient=user.person).order_by('-issued_date')
                    context['invoices'] = patient_invoices
                    context['total_revenue'] = (patient_invoices.filter(status='Paid').aggregate(Sum('total_amount'))['total_amount__sum'] or 0)
                    context['pending_revenue'] = (patient_invoices.filter(status='Unpaid').aggregate(Sum('total_amount'))['total_amount__sum'] or 0)
                else:
                    context['invoices'] = []
        return context

    def post(self, request, *args, **kwargs):
        action = request.POST.get('action')
        try:
            if action == 'create_invoice':
                patient_id = request.POST.get('patient_id')
                amount = request.POST.get('amount')
                if patient_id and amount:
                    patient = PersonDetail.objects.get(id=patient_id)
                    Invoice.objects.create(
                        patient=patient,
                        total_amount=amount,
                        status='Unpaid'
                    )
            elif action == 'make_payment':
                invoice_id = request.POST.get('invoice_id')
                amount = request.POST.get('amount')
                method = request.POST.get('payment_method', 'Online')
                if invoice_id and amount:
                    invoice = Invoice.objects.get(id=invoice_id)
                    Payment.objects.create(
                        invoice=invoice,
                        amount_paid=amount,
                        payment_method=method
                    )
                    invoice.status = 'Paid'
                    invoice.save()
        except Exception as e:
            import logging
            logging.error(f"Billing Final Execution Error: {str(e)}")

        from django.http import HttpResponseRedirect
        return HttpResponseRedirect('/billing/')


# ============================================================
#  Inventory
# ============================================================

class InventoryListView(ListView):
    model = InventoryItem
    template_name = 'management/inventory.html'
    context_object_name = 'inventory_items'

    def post(self, request, *args, **kwargs):
        item_id = request.POST.get('item_id')
        restock_qty = int(request.POST.get('restock_qty', 0))
        if item_id and restock_qty > 0:
            try:
                item = InventoryItem.objects.get(id=item_id)
                item.quantity += restock_qty
                item.save()
                StockTransaction.objects.create(
                    item=item,
                    transaction_type='In',
                    quantity=restock_qty,
                    notes='Manual Template Restock'
                )
            except InventoryItem.DoesNotExist:
                pass
        return redirect('inventory_list')


# ============================================================
#  User Management (Admin only)
# ============================================================

def user_management(request):
    """Admin-only view to list all users and handle user deletion."""
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.role != 'Admin' and not request.user.is_staff:
        return redirect('dashboard')

    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        if user_id:
            try:
                target_user = User.objects.get(id=user_id)
                # Safety: prevent deleting yourself or superusers
                if target_user.id == request.user.id:
                    messages.warning(request, "You cannot delete your own account.")
                elif target_user.is_superuser:
                    messages.warning(request, "Superuser accounts are protected and cannot be deleted.")
                else:
                    username = target_user.username
                    # Also delete linked PersonDetail if exists
                    if hasattr(target_user, 'person') and target_user.person:
                        target_user.person.delete()
                    target_user.delete()
                    messages.success(request, f'User "{username}" has been permanently removed.')
            except User.DoesNotExist:
                messages.error(request, "User not found.")
        return redirect('user_management')

    all_users = User.objects.select_related('person').order_by('-date_joined')
    context = {
        'users': all_users,
        'admin_count': all_users.filter(role='Admin').count() + all_users.filter(is_staff=True, role='').count(),
        'doctor_count': all_users.filter(role='Doctor').count(),
        'patient_count': all_users.filter(role='Patient').count(),
    }
    return render(request, 'management/user_management.html', context)
